#!/bin/sh

#### AUTOSTART ####
pgrep -x sxhkd > /dev/null || sxhkd &


bspc monitor eDP -d I II III IV V
bspc monitor HDMI-A-0 -d VI VII VIII IX X


#### CONFIG ####
bspc config border_width         0
bspc config window_gap          15 
bspc config top_padding  	25

### MOUSE ###
bspc config focus_follows_pointer false
bspc config pointer_follows_focus false
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

### WINDOWS ###
bspc config split_ratio          0.55
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#### BSPWM COLORING ####
bspc config normal_border_color "#4c566a"
bspc config active_border_color "#1e1e1e" #1e1e1e
bspc config focused_border_color "#ff0000" #5e81ac
bspc config presel_feedback_color "#8d65b5"
bspc config urgent_border_color "#dd2727"

#### DEFAULT RULES ####
bspc rule -a zoom state=floating
bspc rule -a Lutris desktop='^2' state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=on


#### Launch more apps ####
picom &
feh --bg-fill --randomize /home/kron/Pictures/ricing/minimal & # Sets the background
$HOME/.config/polybar/launch.sh &
